import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Oswald } from "next/font/google";

const oswald = Oswald({ 
  subsets: ['latin'], 
  weight: ['500', '600', '700'], 
  variable: '--font-oswald',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${oswald.variable} min-h-full flex flex-col bg-[#0B0B0F] text-white`}>

        <Navbar />

        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
